# Generated by Django 5.1.6 on 2025-02-12 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True, verbose_name='资产编号')),
                ('name', models.CharField(max_length=100, verbose_name='资产名称')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='资产类型')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='购置价格')),
                ('purchase_date', models.DateField(verbose_name='购置日期')),
                ('status', models.CharField(choices=[('IN_SOTCK', '在库'), ('LEASING', '领用中'), ('REPAIR', '维修'), ('SCRAPPED', '报废')], default='IN_STOCK', max_length=20, verbose_name='资产状态')),
                ('owner', models.CharField(blank=True, max_length=50, null=True, verbose_name='当前领用人')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='存放位置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('PURCHASE', '购置'), ('LEASE', '领用'), ('RETURN', '归还'), ('REPAIR', '维修'), ('SCRAP', '报废')], max_length=20, verbose_name='变更事件')),
                ('user', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作人')),
                ('location', models.CharField(max_length=100, verbose_name='存放位置')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='assets.asset', verbose_name='关联资产')),
            ],
        ),
    ]
