# Generated by Django 5.1.6 on 2025-02-12 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_rename_asset_id_asset_asset_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='purchase_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='asset',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='品牌'),
        ),
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='型号'),
        ),
        migrations.AddField(
            model_name='asset',
            name='parent_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_assets', to='assets.asset', verbose_name='赠品来源'),
        ),
        migrations.AddField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='序列号'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='资产编号'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(blank=True, choices=[('FIXED', '固定资产'), ('CONSUMABLE', '低值易耗品')], max_length=20, null=True, verbose_name='资产分类'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='资产类别'),
        ),
    ]
