# Generated by Django 5.1.6 on 2025-02-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_rename_purchase_price_asset_price_asset_brand_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetCategory',
        ),
        migrations.DeleteModel(
            name='AssetType',
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(blank=True, choices=[('COMPUTER', '计算设备'), ('MONITOR', '显示器'), ('KEYBOARD', '键盘'), ('MOUSE', '鼠标')], max_length=100, null=True, verbose_name='资产类别'),
        ),
    ]
