# Generated by Django 5.1.6 on 2025-02-14 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('assets', '0005_delete_assetcategory_delete_assettype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='资产类型')),
            ],
        ),
        migrations.RenameField(
            model_name='assethistory',
            old_name='created_at',
            new_name='operated_at',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='parent_asset',
        ),
        migrations.RemoveField(
            model_name='assethistory',
            name='location',
        ),
        migrations.RemoveField(
            model_name='assethistory',
            name='user',
        ),
        migrations.AddField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_assets', to='accounts.department', verbose_name='当前所属部门'),
        ),
        migrations.AddField(
            model_name='assethistory',
            name='from_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assethisstory_from_dep', to='accounts.department', verbose_name='原部门'),
        ),
        migrations.AddField(
            model_name='assethistory',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assethistory_from', to=settings.AUTH_USER_MODEL, verbose_name='原领用人'),
        ),
        migrations.AddField(
            model_name='assethistory',
            name='to_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assethisstory_to_dep', to='accounts.department', verbose_name='新部门'),
        ),
        migrations.AddField(
            model_name='assethistory',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assethisstory_to', to=settings.AUTH_USER_MODEL, verbose_name='新领用人'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_assets', to=settings.AUTH_USER_MODEL, verbose_name='当前领用人'),
        ),
        migrations.AlterField(
            model_name='assethistory',
            name='event',
            field=models.CharField(choices=[('CREATE', '录入'), ('PURCHASE', '购置'), ('TRANSFER', '调拨'), ('ALLOCATE', '领用'), ('RETURN', '归还'), ('REPAIR', '维修'), ('SCRAP', '报废')], max_length=20, verbose_name='变更事件'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.assettype', verbose_name='资产类型'),
        ),
    ]
