# Generated by Django 5.1.6 on 2025-02-14 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_assettype_rename_created_at_assethistory_operated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assethistory',
            old_name='reason',
            new_name='description',
        ),
    ]
