# Generated by Django 5.1.6 on 2025-02-14 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_rename_reason_assethistory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('CREATE', '录入'), ('PURCHASE', '购置'), ('TRANSFER', '调拨'), ('ALLOCATE', '领用'), ('RETURN', '归还'), ('REPAIR', '维修'), ('SCRAP', '报废'), ('UPDATE', '更新'), ('DELETE', '删除')], max_length=20, verbose_name='变更事件')),
                ('operator', models.CharField(max_length=50, verbose_name='操作人')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('operated_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='assets.asset', verbose_name='关联资产')),
            ],
        ),
        migrations.DeleteModel(
            name='AssetHistory',
        ),
    ]
